### PR TITLE
adds support for pyenv

### PR DESCRIPTION
**Pull request by cicorias**
inserts pyenv after python install for managing python installations.

### CODE REVIEW

**Comment by cicorias** [comment]
@crramirez I actually like them distinct from “I just need python” vs “I need a way to do many python envs and pyenv is the way..” .

 But perhaps a sub menu? I think that’s what you mean... let me know and I can squash the menu choice and create the sub menu approach.

**Comment by crramirez** [comment]
Yes I was talking about a submenu or a question at the end of python installation as we do in other installs

**Comment by sirredbeard** [comment]
Thank you for this PR. I like the idea. Note it may not make it into 1.2 as we are wrapping that, with tons of changes, here soon. It might be a candidate for 1.2.1. Just so I can set your expectations.

**Comment by cicorias** [comment]
looking forward to the Pengwin release - I'll refresh and rework when it is released.

**Comment by sirredbeard** [comment]
Thank you! Closed to be re-worked into 1.2.

**Pull request closed without merging**
