### PR TITLE
Add versioning explanation and link to blog

### PR DESCRIPTION
**Pull request by sirredbeard**

### CODE REVIEW

**Comment by sirredbeard** [comment]
The problem is that pengwin-base and pengwin-setup each have their own build numbers, which if an issue arises is more informative than the overall version number. The overall version number is becoming less and less important. It's something we need to work out for sure.

**Comment by sirredbeard** [comment]
Take a look at this latest commit, @kerbe, closer to what you had in mind?

**Comment by kerbe** [comment]
Yes, it is going more to direction what makes it more clear. Still few unclear points that I would like to see clarified:
- where I can see version of pengwin-setup in the repo
- where I can see version of pengwin-base in the repo
- rolling release number, where is that visible in repo (as currently releases/tags have quite unclear version numbers compared for example what is advertised)
- after initial installation, is there need to run pengwin-setup ever again as part of update procedure?
   - this could be different feature request, but would be nice if pengwin-setup remembers selections made previously and shows them when launched again. And it could also doublecheck that selected items are still there, and possibly ask whether they want to be reinstalled in case they are missing?

So basicly as I see my pengwin-base is version 0.1-160 on my computer, what state of repo that represents, and how I see that. Then I can see what new stuff is already done after that, and in case of problems, if they are already addressed and new issue isn't necessary.

As this update started from communication difficulties regarding Pengwin update process and reaching out users with suitable information, there are few more things in my mind:
- I feel that current twitter activity has bad signal to noise ratio. I'm not good twitter user, and might unfollow, but currently it doesn't full fill that need why I followed (to get news about Pengwin development). I wouldn't mind following more curated twitter account, like pengwin-updates, which only tweets about upcoming updates, breaking changes and actions users of Pengwin should take. Community interaction could then happen on main twitter account, like user support, sharing stories and so on.
-  On website it would be nice to have separate News or Changelog feed, which would have similarly only Pengwin development related news. It could be totally fine to use blog for it, just filter these pages with tags. Currently blog has general tech stuff, Fedora Remix and Pengwin Enterprise posts mixed with pure Pengwin information. Separating those, and having directly link to right section in this README.md directs information seekers to right place.

**Comment by sirredbeard** [comment]
Feedback noted. We will more on this.

**Pull request merged**
